CREATE OR REPLACE TRIGGER zmiana_miejsc_trigger
BEFORE UPDATE ON wycieczki
  FOR EACH ROW
  BEGIN
    SELECT :OLD.LICZBA_WOLNYCH_MIEJSC + (:NEW.LICZBA_MIEJSC - :OLD.LICZBA_MIEJSC) INTO :NEW.LICZBA_WOLNYCH_MIEJSC
    FROM Dual;
  END;

  UPDATE WYCIECZKI SET LICZBA_MIEJSC=8
WHERE ID_WYCIECZKI = 1;